name: CI - Full automated build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:   # <-- Manual trigger added here

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run web-ext lint
        run: npx web-ext lint

      - name: Run unit tests (Jest)
        run: npm test

      - name: Package extension
        run: zip -r elsewhere-scraper.zip . -x '*.git*' '*.github*' 'node_modules/*' 'tests/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: elsewhere-scraper-package
          path: elsewhere-scraper.zip
